### ISSUE TITLE
[PE-D] Inconsistent style of User Guide from CLI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#118]
Only the opening brackets are in bold for square brackets while it is bold for both for that of curly brackets. Does not look neat. 

![image.png](https://raw.githubusercontent.com/izdiyadfrhn/ped/main/files/fca1a33e-71ab-4908-a5e2-b0363012ca94.png)

in comparison to:

![image.png](https://raw.githubusercontent.com/izdiyadfrhn/ped/main/files/7e44f3d8-78b3-40c7-9a15-08a89597b877.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: izdiyadfrhn/ped#1

**Comment by richwill28** [comment]
Thanks for the review @izdiyadfrhn.

Note for developer fixing this issue:
This is caused by using shell Markdown.

https://github.com/AY2122S1-CS2113T-W11-3/tp/blob/e951893e879a47d386256ce36263dd9c53ea9bac/docs/UserGuide.md?plain=1#L93

A solution for this is to change it to regular Markdown. For example..

````
```
Markdown content here..
```
````
